[Project]
cubic_version = 2026.02.102-release~202602080449~ubuntu24.04.1
first_version = 2026.02.102-release~202602080449~ubuntu24.04.1
create_date = 2026-05-09 21:25
modify_date = 2026-05-09 22:20
directory = /home/sotauser/SotaOS

[Original]
iso_file_name = ubuntu-24.04.4-live-server-amd64.iso
iso_directory = /mnt/r
iso_volume_id = Ubuntu-Server 24.04.4 LTS amd64
iso_release_name = Noble Numbat
iso_disk_name = 

[Custom]
iso_version_number = 2026.05.09
iso_file_name = ubuntu-24.04.4-2026.05.09-live-server-amd64.iso
iso_directory = /home/sotauser/SotaOS
iso_volume_id = Ubuntu-Server 24.04.4 2026.05.09
iso_release_name = Custom Noble Numbat
iso_disk_name = Ubuntu-Server 24.04.4 2026.05.09 "Custom Noble Numbat"

[Layout]
casper_directory = casper
squashfs_directory = casper
squashfs_file_name = 
manifest_file_name = filesystem.manifest
minimal_remove_file_name = 
standard_remove_file_name = 
size_file_name = filesystem.size
minimal_squashfs_file_name = ubuntu-server-minimal.squashfs
minimal_manifest_file_name = ubuntu-server-minimal.manifest
minimal_size_file_name = ubuntu-server-minimal.size
standard_squashfs_file_name = ubuntu-server-minimal.ubuntu-server.squashfs
standard_manifest_file_name = ubuntu-server-minimal.ubuntu-server.manifest
standard_size_file_name = ubuntu-server-minimal.ubuntu-server.size
installer_sources_file_name = install-sources.yaml
installer_squashfs_file_name = ubuntu-server-minimal.ubuntu-server.installer.squashfs
installer_manifest_file_name = ubuntu-server-minimal.ubuntu-server.installer.manifest
installer_size_file_name = ubuntu-server-minimal.ubuntu-server.installer.size
installer_generic_squashfs_file_name = ubuntu-server-minimal.ubuntu-server.installer.generic.squashfs
installer_generic_manifest_file_name = ubuntu-server-minimal.ubuntu-server.installer.generic.manifest
installer_generic_size_file_name = ubuntu-server-minimal.ubuntu-server.installer.generic.size

[Status]
is_success_analyze = True
is_success_copy = True
is_success_extract = True
iso_template = 789C8D51CD6EE32010BEFB29B8F9B253034E1CDB0FB25734C0D842C2C6021229ADFAEEC5891B75A595760F20F806E6FB19F8CDEA8F5BF0D78594B39F750530C7AB96B0E8C800DC9A29DED08F3E18F46A4A234F20CE697CA7185479B3E55F8FE3BCE5B1FED02164E5169C495917C9E410EF9FCD8631BBECC20AE2CD2DF3CEB1C5904BD9DD08966443028F9A7C05AFA7CADCBD42EFE6958569FA5928D7449989AEB42902600AD110ECCCA83D5580DB46AB55AF0F4C32D95F5A89468869EAAD1442E349738EDC0C2D95A5FF6ED482E0E23CD8F13F8CC9C3D8939C9EF40AD39E4B052E3DB27A82F9BE114389DC72D274D643DB9E4EFDC5F0AED79DBEC86E18CCA502C3EA66677D3398D187BDB93EA0669F50E3DABE83CD34E48B1897C3A1600D40CBD53F02A91E3BF88016927B27763A10B74E018EBC8E79BFF00ABE3B02FA7CF42156FFC8E80F97CFA9C811BD2F49FD434049B4E3D517C156D851
iso_checksum = 
iso_checksum_file_name = 

[Options]
update_os_release = True
has_minimal_install = False
boot_configurations = boot/grub/grub.cfg, boot/grub/loopback.cfg
compression = gzip

